In [1]:
#Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data = pd.read_csv("/content/drive/MyDrive/dataset/report_2018-2019.csv")

In [4]:
data

,Overall rank,Country or region,Year,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,154,Afghanistan,2019,3.203,0.350,0.517,0.361,0.000,0.158,0.025
1,145,Afghanistan,2018,3.632,0.332,0.537,0.255,0.085,0.191,0.036
2,107,Albania,2019,4.719,0.947,0.848,0.874,0.383,0.178,0.027
3,112,Albania,2018,4.586,0.916,0.817,0.790,0.419,0.149,0.032
4,88,Algeria,2019,5.211,1.002,1.160,0.785,0.086,0.073,0.114
...,...,...,...,...,...,...,...,...,...,...
307,152,Yemen,2018,3.355,0.442,1.073,0.343,0.244,0.083,0.064
308,138,Zambia,2019,4.107,0.578,1.058,0.426,0.431,0.247,0.087
309,125,Zambia,2018,4.377,0.562,1.047,0.295,0.503,0.221,0.082
310,146,Zimbabwe,2019,3.663,0.366,1.114,0.433,0.361,0.151,0.089
311,144,Zimbabwe,2018,3.692,0.357,1.094,0.248,0.406,0.132,0.099

In [5]:
data=data.rename(columns={"Overall rank": "Overall_rank",
                          "Country or region": "Country_or_region",
                          "GDP per capita": "GDP_per_capita",
                          "Social support": "Social_support",
                          "Healthy life expectancy": "Healthy_life_expectancy",
                          "Freedom to make life choices": "Freedom_to_make_life_choices",
                          "Perceptions of corruption": "Perceptions_of_corruption"}) # rename the column name

In [6]:
data.head()

,Overall_rank,Country_or_region,Year,Score,GDP_per_capita,Social_support,Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption
0,154,Afghanistan,2019,3.203,0.350,0.517,0.361,0.000,0.158,0.025
1,145,Afghanistan,2018,3.632,0.332,0.537,0.255,0.085,0.191,0.036
2,107,Albania,2019,4.719,0.947,0.848,0.874,0.383,0.178,0.027
3,112,Albania,2018,4.586,0.916,0.817,0.790,0.419,0.149,0.032
4,88,Algeria,2019,5.211,1.002,1.160,0.785,0.086,0.073,0.114

In [7]:
x=data[['Overall_rank','Year','GDP_per_capita','Social_support','Healthy_life_expectancy','Freedom_to_make_life_choices','Generosity','Perceptions_of_corruption']]
y=data['Score']

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=100)

In [9]:
data

,Overall_rank,Country_or_region,Year,Score,GDP_per_capita,Social_support,Healthy_life_expectancy,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption
0,154,Afghanistan,2019,3.203,0.350,0.517,0.361,0.000,0.158,0.025
1,145,Afghanistan,2018,3.632,0.332,0.537,0.255,0.085,0.191,0.036
2,107,Albania,2019,4.719,0.947,0.848,0.874,0.383,0.178,0.027
3,112,Albania,2018,4.586,0.916,0.817,0.790,0.419,0.149,0.032
4,88,Algeria,2019,5.211,1.002,1.160,0.785,0.086,0.073,0.114
...,...,...,...,...,...,...,...,...,...,...
307,152,Yemen,2018,3.355,0.442,1.073,0.343,0.244,0.083,0.064
308,138,Zambia,2019,4.107,0.578,1.058,0.426,0.431,0.247,0.087
309,125,Zambia,2018,4.377,0.562,1.047,0.295,0.503,0.221,0.082
310,146,Zimbabwe,2019,3.663,0.366,1.114,0.433,0.361,0.151,0.089
311,144,Zimbabwe,2018,3.692,0.357,1.094,0.248,0.406,0.132,0.099

In [11]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall_rank                  312 non-null    int64
 1   Year                          312 non-null    int64
 2   GDP_per_capita                312 non-null    float64
 3   Social_support                312 non-null    float64
 4   Healthy_life_expectancy       312 non-null    float64
 5   Freedom_to_make_life_choices  312 non-null    float64
 6   Generosity                    312 non-null    float64
 7   Perceptions_of_corruption     312 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 19.6 KB

In [12]:
data['Score'].unique()

array([3.203, 3.632, 4.719, 4.586, 5.211, 5.295, 3.795, 6.086, 6.388,
       4.559, 4.321, 7.228, 7.272, 7.246, 7.139, 5.208, 5.201, 6.199,
       6.105, 4.456, 4.5  , 5.323, 5.483, 6.923, 6.927, 5.956, 4.883,
       4.141, 5.082, 5.779, 5.752, 5.386, 5.129, 3.488, 3.59 , 6.3  ,
       6.419, 5.011, 4.933, 4.587, 4.424, 3.775, 2.905, 4.7  , 4.433,
       5.044, 4.975, 7.278, 7.328, 3.083, 4.35 , 4.301, 6.444, 6.476,
       5.191, 5.246, 6.125, 6.26 , 3.973, 4.812, 4.418, 4.245, 7.167,
       7.072, 5.432, 5.321, 6.046, 5.762, 6.852, 6.711, 7.6  , 7.555,
       5.425, 5.302, 6.028, 5.973, 4.166, 4.419, 6.253, 6.167, 5.893,
       5.739, 4.286, 7.769, 7.632, 6.592, 6.489, 4.799, 4.758, 4.516,
       4.519, 4.34 , 6.985, 6.965, 4.996, 4.657, 5.287, 5.358, 6.436,
       6.382, 4.534, 3.964, 3.597, 3.582, 5.86 , 5.504, 5.43 , 5.758,
       5.62 , 7.494, 7.495, 4.015, 4.19 , 5.192, 5.093, 4.548, 4.707,
       4.437, 7.021, 6.977, 6.814, 6.223, 6.   , 4.944, 4.671, 5.89 ,
       5.886, 5.915, 4.906, 5.161, 5.809, 5.79 , 4.509, 4.41 , 6.1  ,
       5.662, 6.021, 6.083, 5.261, 5.131, 4.796, 4.623, 5.94 , 5.933,
       5.197, 3.802, 3.808, 3.975, 3.495, 5.525, 5.566, 6.149, 5.952,
       7.09 , 6.91 , 5.185, 3.933, 3.774, 3.41 , 3.587, 5.339, 6.322,
       4.39 , 4.447, 6.726, 6.627, 4.49 , 4.356, 5.888, 5.891, 6.595,
       6.488, 5.529, 5.64 , 5.285, 5.125, 5.523, 5.347, 5.254, 4.466,
       4.417, 4.36 , 4.308, 4.639, 4.441, 4.913, 4.88 , 7.488, 7.441,
       7.307, 7.324, 6.141, 4.628, 5.265, 5.155, 5.274, 5.718, 5.835,
       7.554, 7.594, 5.653, 5.472, 4.696, 4.743, 6.321, 6.43 , 5.743,
       5.681, 5.697, 5.663, 5.631, 5.524, 6.182, 6.123, 5.693, 5.41 ,
       6.374, 6.07 , 5.945, 5.648, 5.81 , 3.334, 3.408, 6.375, 6.371,
       4.681, 4.631, 5.603, 5.398, 4.374, 4.571, 6.262, 6.343, 6.198,
       6.173, 6.118, 5.948, 4.668, 4.982, 4.722, 4.724, 5.895, 5.875,
       2.853, 3.254, 6.354, 6.31 , 4.366, 4.471, 4.139, 4.212, 7.343,
       7.314, 7.48 , 7.487, 3.462, 6.446, 6.441, 5.467, 5.199, 3.231,
       3.303, 6.008, 6.072, 4.085, 3.999, 6.192, 4.461, 4.592, 5.373,
       5.247, 5.636, 4.189, 4.161, 4.332, 4.103, 6.825, 6.774, 7.054,
       7.19 , 6.892, 6.886, 6.293, 6.379, 6.174, 6.096, 4.806, 5.175,
       5.103, 3.38 , 3.355, 4.107, 4.377, 3.663, 3.692])

In [13]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()  
mlr.fit(x_train, y_train)

LinearRegression()

In [14]:
print("Intercept: ",mlr.intercept_)
print("coefficients: ")
list(zip(x,mlr.coef_))

Intercept:  -36.070291273862935
coefficients:

[('Overall_rank', -0.02283005149663667),
 ('Year', 0.021219174838469912),
 ('GDP_per_capita', -0.030480226556336795),
 ('Social_support', 0.2227332015587178),
 ('Healthy_life_expectancy', 0.05228527994697603),
 ('Freedom_to_make_life_choices', 0.12771092648744428),
 ('Generosity', 0.24935759097272608),
 ('Perceptions_of_corruption', 0.36278993396293036)]

In [15]:
#prediction of test set
y_pred_mlr=mlr.predict(x_test)
#predicted values
print("prediction for test set: {}".format(y_pred_mlr))

prediction for test set: [4.27683844 5.35013212 3.63401029 3.85014526 6.95562951 6.12469212
 3.83102283 6.24602235 4.39516395 4.10585906 6.24935482 5.03120852
 6.07999158 6.10475011 6.98089992 6.82256902 4.48041837 5.54710895
 4.05748649 5.35797138 6.50304259 4.87884156 4.49374848 5.4634423
 5.8215072  6.03901797 5.0357536  4.89150874 6.50934129 3.84421847
 6.5098997  7.22041181 5.92803345 4.35919227 6.00292486 5.14198149
 5.93947725 3.8506966  5.06921265 7.01106198 4.46739924 5.01993001
 3.78523204 5.67502257 7.24416594 5.63295315 6.54623012 7.05061703
 6.41965032 7.01508737 5.0999914  6.05504061 5.59744351 7.26529453
 5.07939196 5.5081476  4.44679088 5.80492371 4.94251175 7.36760321
 3.66683688 3.47719552 5.25117761 6.881985   5.77091864 4.0979464
 3.8052038  6.60787792 4.6705408  6.97796447 3.64773259 4.3208662
 4.30541105 6.06794845 4.36553581 6.33639457 5.92874686 6.37543429
 5.90868434 6.20407084 4.32149576 4.50845036 3.9615542  5.3706411
 6.21299692 5.95963664 4.02776938 3.67401741 6.98453005 4.71116945
 6.58606625 4.74946008 7.24794875 7.17946833]

In [16]:
#actual value and the predicted value
mlr_diff = pd.DataFrame({'Actual value': y_test, 'predicted value': y_pred_mlr})
mlr_diff.head()

     Actual value  predicted value
309         4.377         4.276838
169         5.339         5.350132
1           3.632         3.634010
27          4.141         3.850145
126         7.139         6.955630

In [17]:
#model Evaluation 
from sklearn import metrics
meanSqErr = metrics.mean_squared_error(y_test,y_pred_mlr)
print('R squared: {Mean Square Error: }',meanSqErr)

R squared: {Mean Square Error: } 0.018745773189011425