In [ ]:
#Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/dataset/column_2C_weka.csv")
# data = pd.read_csv("/content/drive/MyDrive/dataset/column_2C_weka.csv")

In [ ]:
data

,pelvic_incidence,pelvic_tilt numeric,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,class
0,63.027817,22.552586,39.609117,40.475232,98.672917,-0.254400,Abnormal
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,Abnormal
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,Abnormal
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,Abnormal
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,Abnormal
...,...,...,...,...,...,...,...
305,47.903565,13.616688,36.000000,34.286877,117.449062,-4.245395,Normal
306,53.936748,20.721496,29.220534,33.215251,114.365845,-0.421010,Normal
307,61.446597,22.694968,46.170347,38.751628,125.670725,-2.707880,Normal
308,45.252792,8.693157,41.583126,36.559635,118.545842,0.214750,Normal
309,33.841641,5.073991,36.641233,28.767649,123.945244,-0.199249,Normal

In [ ]:
data=data.rename(columns={"pelvic_tilt numeric": "pelvic_tilt"}) # rename the column name

In [ ]:
data.head()

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,class
0,63.027817,22.552586,39.609117,40.475232,98.672917,-0.254400,Abnormal
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,Abnormal
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,Abnormal
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,Abnormal
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,Abnormal

In [ ]:
data['class']=[1 if each=="Abnormal" else 0 for each in data['class']]

In [ ]:
x=data[['pelvic_incidence','pelvic_tilt','lumbar_lordosis_angle','sacral_slope','pelvic_radius','degree_spondylolisthesis']]
y=data['class']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=100)

In [ ]:
data

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,class
0,63.027817,22.552586,39.609117,40.475232,98.672917,-0.254400,1
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,1
2,68.832021,22.218482,50.092194,46.613539,105.985135,-3.530317,1
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,1
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,1
...,...,...,...,...,...,...,...
305,47.903565,13.616688,36.000000,34.286877,117.449062,-4.245395,0
306,53.936748,20.721496,29.220534,33.215251,114.365845,-0.421010,0
307,61.446597,22.694968,46.170347,38.751628,125.670725,-2.707880,0
308,45.252792,8.693157,41.583126,36.559635,118.545842,0.214750,0
309,33.841641,5.073991,36.641233,28.767649,123.945244,-0.199249,0

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pelvic_incidence          310 non-null    float64
 1   pelvic_tilt               310 non-null    float64
 2   lumbar_lordosis_angle     310 non-null    float64
 3   sacral_slope              310 non-null    float64
 4   pelvic_radius             310 non-null    float64
 5   degree_spondylolisthesis  310 non-null    float64
dtypes: float64(6)
memory usage: 14.7 KB

In [ ]:
data['class'].unique()

array([1, 0])

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()  
mlr.fit(x_train, y_train)

LinearRegression()

In [ ]:
print("Intercept: ",mlr.intercept_)
print("coefficients: ")
list(zip(x,mlr.coef_))

Intercept:  2.0630711104383925
coefficients:

[('pelvic_incidence', -2810557.773821225),
 ('pelvic_tilt', 2810557.783352672),
 ('lumbar_lordosis_angle', 0.0033217158634215593),
 ('sacral_slope', 2810557.7660022285),
 ('pelvic_radius', -0.012747695960570127),
 ('degree_spondylolisthesis', 0.0048442417755723)]

In [ ]:
#prediction of test set
y_pred_mlr=mlr.predict(x_test)
#predicted values
print("prediction for test set: {}".format(y_pred_mlr))

prediction for test set: [1.24210992 0.41667517 0.15464567 0.54838611 0.91499142 1.31771933
 0.5146231  1.2049028  0.47838092 0.75337769 0.23518936 0.81547062
 0.51810266 1.19308851 0.49594122 0.59079005 0.01883871 0.53366445
 0.66174916 0.68110292 1.09305654 0.46306705 0.6715392  1.02078988
 0.70858001 0.78244547 0.62091145 0.33704847 0.57519803 0.72602206
 0.82043248 0.4877768  0.27834607 0.54827224 0.4082776  0.37588161
 0.37515992 1.51210358 0.43224646 0.23834228 1.30109521 0.5913055
 0.72922134 0.4760398  0.71786649 0.73299408 0.77983452 0.46993034
 0.59454081 0.74112559 0.51348309 0.6066609  0.90521261 0.51016638
 1.12634981 0.68132771 0.68336515 0.58966673 1.46203776 0.32311358
 0.50625096 0.90662017 0.57904638 0.65752868 0.58184027 0.77516599
 0.65105622 0.99173823 0.51700813 0.9689416  0.55722966 1.28070206
 0.47983863 0.52116327 0.37217521 0.64829397 0.92256201 0.70244213
 0.59171012 0.66038498 0.89005125 0.62965219 0.64037215 0.42458732
 1.07659869 0.86374297 1.04311956 0.44816198 0.92730041 0.25939271
 0.04310967 0.7711122  0.94017136]

In [ ]:
#actual value and the predicted value
mlr_diff = pd.DataFrame({'Actual value': y_test, 'predicted value': y_pred_mlr})
mlr_diff.head()

     Actual value  predicted value
75              1         1.242110
7               1         0.416675
250             0         0.154646
56              1         0.548386
149             1         0.914991

In [ ]:
#model Evaluation 
from sklearn import metrics
meanSqErr = metrics.mean_squared_error(y_test,y_pred_mlr)
print('R squared: {Mean Square Error: }',meanSqErr)

R squared: {Mean Square Error: } 0.1642842296946446